resource:
  url: http://shop.tomatostores.com/api
  username: modaapimolo
  password: kS#n+m6sy7
  headerName: X-Oc-Restadmin-Id
  authorization: CXAaZmtcDSop1u80esyarB0HMpaNo7i2

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
        web: ERROR
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG
  file: ../mylogfile.log
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'

job:
  timeInterval: 5000

xml:
  pathKey: ':: record ::'
